### ISSUE TITLE
wishlist: translating body

### ISSUE THREAD

**Issue by SamMallinson** [fmuni/openHFDIB#2]
I've created a translatingBody method inside immersedBody.C, and added a tutorial called movingCylinder which might satisfy this request

https://github.com/SamMallinson/openHFDIB/tree/translatingBody

**Comment by drs261083** [comment]
Hello,

I would like to thank you for developing this solver and making it available on Github. I compiled the solver in OpenFOAM 4.0 and successfully ran the cylinder and impeller tutorials. I was interested in extending this solver for fluid-structure interaction simulations involving compliant solid bodies. I would like to know whether it is possible to compute the three-dimensional forces acting on each node of the immersed structural domain (input as a triangulated STL file) that could be communicated to a third-party solid mechanics solver for computation of displacements and stresses.  

Regards

**Comment by SamMallinson** [comment]
Hi drs261083,

> I would like to know whether it is possible to compute the three-dimensional forces acting on each node of the immersed structural domain (input as a triangulated STL file) that could be communicated to a third-party solid mechanics solver for computation of displacements and stresses

Not sure if it is possible, but I guess it is - I have never looked at FSI with OpenFOAM.

I believe there are some OpenFOAM-based FSI solvers out there; see, for example, this discussion on cfd-online:

https://www.cfd-online.com/Forums/openfoam-solving/138487-problem-case-icofsifoam-foam-extend-3-1-a.html

and this entry on openfoamwiki (for foam-extend)

https://openfoamwiki.net/index.php/Extend-bazaar/Toolkits/Fluid-structure_interaction

Best of luck!

Cheers,

Sam

**Comment by fmuni** [comment]
You can use OpenFOAM interpolation functions to compute the forces acting on the nodes (basically, like in https://github.com/fmuni/openHFDIB/blob/master/src/openHFDIB.C#L124).
Then you can create pointVectorFields and make use of the body triSurfaceMesh for implementing some kind of membrane solver (perhaps like in http://www.sciencedirect.com/science/article/pii/S0021999106002245).

Probably it is not easy, but it is definitely possible in OpenFOAM.

**Comment by fmuni** [comment]
I would say we can close the translating body issue.

**Comment by SamMallinson** [comment]
Hi Federico,

I am not sure drs261083's comment is on topic - I think he was asking about using the translatingBody part of the code for his fsi problem.

I still think the translatingBody code I contributed should be part of openHFDIBFoam - it was a simple addition that works well.

Cheers,

Sam

**Comment by fmuni** [comment]
Hi Sam,

thanks for your contributions.

> I still think the translatingBody code I contributed should be part of openHFDIBFoam - it was a simple addition that works well.

I recently implemented a transRotatingBody bodyOperation that combines rotation and translation of the immersed body. Now you can have bodies that translate and rotate at the same time!

> I am not sure drs261083's comment is on topic - I think he was asking about using the translatingBody part of the code for his fsi problem.

I think that comment is related with having the interphase force interpolated at the stl nodes. One may use those values as boundary condition for a structural solver.
This is possible, I will open a separate issue on that. Maybe I can find some time to couple the immersed boundary with a FV solver (in OpenFOAM-5) or a steadyState linear elasticity FEM solver (in  foam-extend-4.0). However, real FSI is a huge beast and people from the Immersed Boundary community tend to avoid it and they prefer to employ simple shell models.
